services:
  # Base image containing dependencies.
  base:
    image: xarm_control:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: jazzy
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: true
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
 
  # Simulation image containing the example source code.
  overlay:
    extends: base
    image: xarm_control:overlay
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay

  # xarm robot simulation.
  # sim:
  #   extends: overlay
  #   command: >
  #     ros2 launch xarm_gazebo sim_xarm.launch.py

  # # Simulation image containing the example source code.
  # real:
  #   extends: overlay
  #   command: >
  #     ros2 launch xarm_bringup start_xarm.launch.py

  # Development container
  dev:
    extends: overlay
    image: xarm_control:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_UID:-1000}
        # Set correct USERNAME
        # - USERNAME=${USERNAME:-ubuntu}
    volumes:
      # Mount colcon build artifacts for faster rebuilds
      - ./.colcon/build/:/overlay_ws/build/:rw
      - ./.colcon/install/:/overlay_ws/install/:rw
      - ./.colcon/log/:/overlay_ws/log/:rw
      # Mount source code
      - ./xarm_description/:/overlay_ws/src/xarm_description/:rw
      - ./xarm_moveit_config/:/overlay_ws/src/xarm_moveit_config/:rw
      - ./xarm_gazebo/:/overlay_ws/src/xarm_gazebo/:rw
      - ./xarm_bringup/:/overlay_ws/src/xarm_bringup/:rw
      - ./xarm_control/:/overlay_ws/src/xarm_control/:rw
      - ./xarm_app/:/overlay_ws/src/xarm_app/:rw
      - ./xarm_behavior/:/overlay_ws/src/xarm_behavior/:rw
      - /dev:/dev
    # user: ${USERNAME:-ubuntu}
    command: sleep infinity