# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm_controller
    - xgripper_controller

  xarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - xarm_6_joint
      - xarm_5_joint
      - xarm_4_joint
      - xarm_3_joint
      - xarm_2_joint
  xgripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - finger_l_joint
      - finger_r_joint