# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    xarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    xgripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

xarm_controller:
  ros__parameters:
    joints:
      - xarm_6_joint
      - xarm_5_joint
      - xarm_4_joint
      - xarm_3_joint
      - xarm_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
xgripper_controller:
  ros__parameters:
    joints:
      - finger_l_joint
      - finger_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity